// Code generated by locking.bzl. DO NOT EDIT.

package channel

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type queueRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *queueRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *queueRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *queueRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *queueRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *queueRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *queueRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *queueRWMutex) RLocker() sync.Locker {
	return (*queueRWMutexRLocker)(m)
}

type queueRWMutexRLocker queueRWMutex

func (r *queueRWMutexRLocker) Lock()   { (*queueRWMutex)(r).RLock() }
func (r *queueRWMutexRLocker) Unlock() { (*queueRWMutex)(r).RUnlock() }

