apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: whispera
data:
  config.yaml: |
    listen: "{{ .Values.server.listenAddr }}"
    api:
      enabled: true
      listen_addr: "{{ .Values.server.apiAddr }}"
    modules:
      handshake:
        enabled: true
      tunnel:
        enabled: true
      metrics:
        enabled: true
        listen_addr: ":9090"
