// Copyright 2020 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package stack

import (
	"context"
	"fmt"

	"gvisor.dev/gvisor/pkg/atomicbitops"
)

// enableLoggingAddressState indicates whether reference-related events should be logged (with
// stack traces). This is false by default and should only be set to true for
// debugging purposes, as it can generate an extremely large amount of output
// and drastically degrade performance.
const enableLoggingAddressState = false

// objAddressState is used to customize logging. Note that we use a pointer to addressState so that
// we do not copy the entire object when passed as a format parameter.
var objAddressState *addressState

// addressStateRefs implements refs.RefCounter. It keeps a reference count using atomic
// operations and calls the destructor when the count reaches zero.
//
// +stateify savable
type addressStateRefs struct {
	// refCount is composed of two fields:
	//
	//	[32-bit speculative references]:[32-bit real references]
	//
	// Speculative references are used for TryIncRef, to avoid a CompareAndSwap
	// loop. See IncRef, DecRef and TryIncRef for details of how these fields are
	// used.
	refCount atomicbitops.Int64
}

// InitRefs initializes r with one reference and, if enabled, activates leak
// checking.
func (r *addressStateRefs) InitRefs() {
	// We can use RacyStore because the refs can't be shared until after
	// InitRefs is called, and thus it's safe to use non-atomic operations.
	r.refCount.RacyStore(1)
	// Note: refs.Register is disabled for now to avoid import conflicts
	// refs.Register(r)
}

// RefType implements refs.CheckedObject.RefType.
func (r *addressStateRefs) RefType() string {
	return fmt.Sprintf("%T", objAddressState)[1:]
}

// LeakMessage implements refs.CheckedObject.LeakMessage.
func (r *addressStateRefs) LeakMessage() string {
	return fmt.Sprintf("[%s %p] reference count of %d instead of 0", r.RefType(), r, r.ReadRefs())
}

// LogRefs implements refs.CheckedObject.LogRefs.
func (r *addressStateRefs) LogRefs() bool {
	return enableLogging
}

// ReadRefs returns the current number of references. The returned count is
// inherently racy and is unsafe to use without external synchronization.
func (r *addressStateRefs) ReadRefs() int64 {
	return r.refCount.Load()
}

// IncRef implements refs.RefCounter.IncRef.
//
//go:nosplit
func (r *addressStateRefs) IncRef() {
	v := r.refCount.Add(1)
	if enableLoggingAddressState {
		// refs.LogIncRef(r, v)
	}
	if v <= 1 {
		panic(fmt.Sprintf("Incrementing non-positive count %p on %s", r, r.RefType()))
	}
}

// TryIncRef implements refs.TryRefCounter.TryIncRef.
//
//go:nosplit
func (r *addressStateRefs) TryIncRef() bool {
	const speculativeRef = 1 << 32
	if v := r.refCount.Add(speculativeRef); int32(v) == 0 {
		// This object has already been freed.
		r.refCount.Add(-speculativeRef)
		return false
	}

	// Turn into a real reference.
	r.refCount.Add(-speculativeRef + 1)
	if enableLoggingAddressState {
		// refs.LogTryIncRef(r, v)
	}
	return true
}

// DecRef implements refs.RefCounter.DecRef.
//
//go:nosplit
func (r *addressStateRefs) DecRef(destroy func()) {
	v := r.refCount.Add(-1)
	if enableLoggingAddressState {
		// refs.LogDecRef(r, v)
	}
	switch {
	case v < 0:
		panic(fmt.Sprintf("Decrementing non-positive ref count %p, owned by %s", r, r.RefType()))

	case v == 0:
		// refs.Unregister(r)
		// Call the destructor.
		if destroy != nil {
			destroy()
		}
	}
}

func (r *addressStateRefs) afterLoad(context.Context) {
	if r.ReadRefs() > 0 {
		// refs.Register(r)
	}
}

