// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// bucketLockOthertuple is used for nested locking of bucket mutex.
const bucketLockOthertuple = 0

// +checklocksignore
type bucketRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *bucketRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *bucketRWMutex) NestedLock(i int) {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *bucketRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *bucketRWMutex) NestedUnlock(i int) {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *bucketRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *bucketRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *bucketRWMutex) RLocker() sync.Locker {
	return (*bucketRWMutexRLocker)(m)
}

type bucketRWMutexRLocker bucketRWMutex

func (r *bucketRWMutexRLocker) Lock()   { (*bucketRWMutex)(r).RLock() }
func (r *bucketRWMutexRLocker) Unlock() { (*bucketRWMutex)(r).RUnlock() }

