// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type neighborCacheRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *neighborCacheRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *neighborCacheRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *neighborCacheRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *neighborCacheRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *neighborCacheRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *neighborCacheRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *neighborCacheRWMutex) RLocker() sync.Locker {
	return (*neighborCacheRWMutexRLocker)(m)
}

type neighborCacheRWMutexRLocker neighborCacheRWMutex

func (r *neighborCacheRWMutexRLocker) Lock()   { (*neighborCacheRWMutex)(r).RLock() }
func (r *neighborCacheRWMutexRLocker) Unlock() { (*neighborCacheRWMutex)(r).RUnlock() }

