// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type neighborEntryRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *neighborEntryRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *neighborEntryRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *neighborEntryRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *neighborEntryRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *neighborEntryRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *neighborEntryRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *neighborEntryRWMutex) RLocker() sync.Locker {
	return (*neighborEntryRWMutexRLocker)(m)
}

type neighborEntryRWMutexRLocker neighborEntryRWMutex

func (r *neighborEntryRWMutexRLocker) Lock()   { (*neighborEntryRWMutex)(r).RLock() }
func (r *neighborEntryRWMutexRLocker) Unlock() { (*neighborEntryRWMutex)(r).RUnlock() }

