// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package stack

// neighborEntryEntry is an entry in a neighborEntryList.
type neighborEntryEntry struct {
	next *neighborEntry
	prev *neighborEntry
}

// Next returns the entry that follows e in the list.
func (e *neighborEntryEntry) Next() *neighborEntry {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *neighborEntryEntry) Prev() *neighborEntry {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *neighborEntryEntry) SetNext(entry *neighborEntry) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *neighborEntryEntry) SetPrev(entry *neighborEntry) {
	e.prev = entry
}

// neighborEntryList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for neighborEntryList is an empty list ready to use.
type neighborEntryList struct {
	head *neighborEntry
	tail *neighborEntry
}

// Reset resets list l to the empty state.
func (l *neighborEntryList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *neighborEntryList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *neighborEntryList) Front() *neighborEntry {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *neighborEntryList) Back() *neighborEntry {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *neighborEntryList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *neighborEntryList) PushFront(e *neighborEntry) {
	linker := &e.neighborEntryEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.neighborEntryEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *neighborEntryList) PushBack(e *neighborEntry) {
	linker := &e.neighborEntryEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.neighborEntryEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// Remove removes e from l.
func (l *neighborEntryList) Remove(e *neighborEntry) {
	linker := &e.neighborEntryEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.neighborEntryEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.neighborEntryEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

