// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type nicRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *nicRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *nicRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *nicRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *nicRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *nicRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *nicRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *nicRWMutex) RLocker() sync.Locker {
	return (*nicRWMutexRLocker)(m)
}

type nicRWMutexRLocker nicRWMutex

func (r *nicRWMutexRLocker) Lock()   { (*nicRWMutex)(r).RLock() }
func (r *nicRWMutexRLocker) Unlock() { (*nicRWMutex)(r).RUnlock() }

