// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type packetsPendingLinkResolutionMutex struct {
	mu sync.Mutex
}

// Lock locks m.
// +checklocksignore
func (m *packetsPendingLinkResolutionMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetsPendingLinkResolutionMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *packetsPendingLinkResolutionMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetsPendingLinkResolutionMutex) NestedUnlock() {
	m.mu.Unlock()
}

