// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type packetEPsRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *packetEPsRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetEPsRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *packetEPsRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetEPsRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *packetEPsRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *packetEPsRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *packetEPsRWMutex) RLocker() sync.Locker {
	return (*packetEPsRWMutexRLocker)(m)
}

type packetEPsRWMutexRLocker packetEPsRWMutex

func (r *packetEPsRWMutexRLocker) Lock()   { (*packetEPsRWMutex)(r).RLock() }
func (r *packetEPsRWMutexRLocker) Unlock() { (*packetEPsRWMutex)(r).RUnlock() }

