// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type packetEndpointListRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *packetEndpointListRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetEndpointListRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *packetEndpointListRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetEndpointListRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *packetEndpointListRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *packetEndpointListRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *packetEndpointListRWMutex) RLocker() sync.Locker {
	return (*packetEndpointListRWMutexRLocker)(m)
}

type packetEndpointListRWMutexRLocker packetEndpointListRWMutex

func (r *packetEndpointListRWMutexRLocker) Lock()   { (*packetEndpointListRWMutex)(r).RLock() }
func (r *packetEndpointListRWMutexRLocker) Unlock() { (*packetEndpointListRWMutex)(r).RUnlock() }

