// Code generated by locking.bzl. DO NOT EDIT.

package stack

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type transportEndpointsRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *transportEndpointsRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *transportEndpointsRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *transportEndpointsRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *transportEndpointsRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *transportEndpointsRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *transportEndpointsRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *transportEndpointsRWMutex) RLocker() sync.Locker {
	return (*transportEndpointsRWMutexRLocker)(m)
}

type transportEndpointsRWMutexRLocker transportEndpointsRWMutex

func (r *transportEndpointsRWMutexRLocker) Lock()   { (*transportEndpointsRWMutex)(r).RLock() }
func (r *transportEndpointsRWMutexRLocker) Unlock() { (*transportEndpointsRWMutex)(r).RUnlock() }

