// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package tcpip

// RouteEntry is an entry in a RouteList.
type RouteEntry struct {
	next *Route
	prev *Route
}

// Next returns the entry that follows e in the list.
func (e *RouteEntry) Next() *Route {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *RouteEntry) Prev() *Route {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *RouteEntry) SetNext(entry *Route) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *RouteEntry) SetPrev(entry *Route) {
	e.prev = entry
}

// RouteList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for RouteList is an empty list ready to use.
type RouteList struct {
	head *Route
	tail *Route
}

// Reset resets list l to the empty state.
func (l *RouteList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *RouteList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *RouteList) Front() *Route {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *RouteList) Back() *Route {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *RouteList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *RouteList) PushFront(e *Route) {
	linker := &e.RouteEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.RouteEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *RouteList) PushBack(e *Route) {
	linker := &e.RouteEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.RouteEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// InsertBefore inserts e before a.
func (l *RouteList) InsertBefore(a, e *Route) {
	aLinker := &a.RouteEntry
	eLinker := &e.RouteEntry

	b := aLinker.Prev()
	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	aLinker.SetPrev(e)

	if b != nil {
		(&b.RouteEntry).SetNext(e)
	} else {
		l.head = e
	}
}

// Remove removes e from l.
func (l *RouteList) Remove(e *Route) {
	linker := &e.RouteEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.RouteEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.RouteEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

