// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package tcpip

// sockErrorEntry is an entry in a sockErrorList.
type sockErrorEntry struct {
	next *SockError
	prev *SockError
}

// Next returns the entry that follows e in the list.
func (e *sockErrorEntry) Next() *SockError {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *sockErrorEntry) Prev() *SockError {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *sockErrorEntry) SetNext(entry *SockError) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *sockErrorEntry) SetPrev(entry *SockError) {
	e.prev = entry
}

// sockErrorList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for sockErrorList is an empty list ready to use.
type sockErrorList struct {
	head *SockError
	tail *SockError
}

// Reset resets list l to the empty state.
func (l *sockErrorList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *sockErrorList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *sockErrorList) Front() *SockError {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *sockErrorList) Back() *SockError {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *sockErrorList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *sockErrorList) PushFront(e *SockError) {
	linker := &e.sockErrorEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.sockErrorEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *sockErrorList) PushBack(e *SockError) {
	linker := &e.sockErrorEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.sockErrorEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// Remove removes e from l.
func (l *sockErrorList) Remove(e *SockError) {
	linker := &e.sockErrorEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.sockErrorEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.sockErrorEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

