// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package waiter

// waiterEntry is an entry in a waiterList.
type waiterEntry struct {
	next *Entry
	prev *Entry
}

// Next returns the entry that follows e in the list.
func (e *waiterEntry) Next() *Entry {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *waiterEntry) Prev() *Entry {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *waiterEntry) SetNext(entry *Entry) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *waiterEntry) SetPrev(entry *Entry) {
	e.prev = entry
}

// waiterList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for waiterList is an empty list ready to use.
//
// To iterate over a list (where l is a waiterList):
//
//	for e := l.Front(); e != nil; e = e.Next() {
//		// do something with e.
//	}
type waiterList struct {
	head *Entry
	tail *Entry
}

// Reset resets list l to the empty state.
func (l *waiterList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *waiterList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *waiterList) Front() *Entry {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *waiterList) Back() *Entry {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *waiterList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *waiterList) PushFront(e *Entry) {
	linker := &e.waiterEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.waiterEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *waiterList) PushBack(e *Entry) {
	linker := &e.waiterEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.waiterEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// InsertAfter inserts e after b.
func (l *waiterList) InsertAfter(b, e *Entry) {
	bLinker := &b.waiterEntry
	eLinker := &e.waiterEntry

	a := bLinker.Next()

	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	bLinker.SetNext(e)

	if a != nil {
		(&a.waiterEntry).SetPrev(e)
	} else {
		l.tail = e
	}
}

// InsertBefore inserts e before a.
func (l *waiterList) InsertBefore(a, e *Entry) {
	aLinker := &a.waiterEntry
	eLinker := &e.waiterEntry

	b := aLinker.Prev()
	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	aLinker.SetPrev(e)

	if b != nil {
		(&b.waiterEntry).SetPrev(e)
	} else {
		l.head = e
	}
}

// Remove removes e from l.
func (l *waiterList) Remove(e *Entry) {
	linker := &e.waiterEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.waiterEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.waiterEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

// PushFrontList inserts list m at the start of list l, emptying m.
func (l *waiterList) PushFrontList(m *waiterList) {
	if l.head == nil {
		l.head = m.head
		l.tail = m.tail
	} else if m.head != nil {
		(&l.head.waiterEntry).SetPrev(m.tail)
		(&m.tail.waiterEntry).SetNext(l.head)
		l.head = m.head
	}
	m.head = nil
	m.tail = nil
}

// PushBackList inserts list m at the end of list l, emptying m.
func (l *waiterList) PushBackList(m *waiterList) {
	if l.head == nil {
		l.head = m.head
		l.tail = m.tail
	} else if m.head != nil {
		(&l.tail.waiterEntry).SetNext(m.head)
		(&m.head.waiterEntry).SetPrev(l.tail)
		l.tail = m.tail
	}
	m.head = nil
	m.tail = nil
}

