// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package buffer

// ViewEntry is an entry in a ViewList.
type ViewEntry struct {
	next *View
	prev *View
}

// Next returns the entry that follows e in the list.
func (e *ViewEntry) Next() *View {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *ViewEntry) Prev() *View {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *ViewEntry) SetNext(entry *View) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *ViewEntry) SetPrev(entry *View) {
	e.prev = entry
}

// ViewList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for ViewList is an empty list ready to use.
//
// To iterate over a list (where l is a ViewList):
//
//	for e := l.Front(); e != nil; e = e.Next() {
//		// do something with e.
//	}
type ViewList struct {
	head *View
	tail *View
}

// Reset resets list l to the empty state.
func (l *ViewList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *ViewList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *ViewList) Front() *View {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *ViewList) Back() *View {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *ViewList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *ViewList) PushFront(e *View) {
	linker := &e.ViewEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.ViewEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *ViewList) PushBack(e *View) {
	linker := &e.ViewEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.ViewEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// InsertAfter inserts e after b.
func (l *ViewList) InsertAfter(b, e *View) {
	bLinker := &b.ViewEntry
	eLinker := &e.ViewEntry

	a := bLinker.Next()

	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	bLinker.SetNext(e)

	if a != nil {
		(&a.ViewEntry).SetPrev(e)
	} else {
		l.tail = e
	}
}

// InsertBefore inserts e before a.
func (l *ViewList) InsertBefore(a, e *View) {
	aLinker := &a.ViewEntry
	eLinker := &e.ViewEntry

	b := aLinker.Prev()
	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	aLinker.SetPrev(e)

	if b != nil {
		(&b.ViewEntry).SetNext(e)
	} else {
		l.head = e
	}
}

// Remove removes e from l.
func (l *ViewList) Remove(e *View) {
	linker := &e.ViewEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.ViewEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.ViewEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

// PushFrontList inserts list m at the start of list l, emptying m.
func (l *ViewList) PushFrontList(m *ViewList) {
	if l.head == nil {
		l.head = m.head
		l.tail = m.tail
	} else if m.head != nil {
		(&l.head.ViewEntry).SetPrev(m.tail)
		(&m.tail.ViewEntry).SetNext(l.head)
		l.head = m.head
	}
	m.head = nil
	m.tail = nil
}

// PushBackList inserts list m at the end of list l, emptying m.
func (l *ViewList) PushBackList(m *ViewList) {
	if l.head == nil {
		l.head = m.head
		l.tail = m.tail
	} else if m.head != nil {
		(&l.tail.ViewEntry).SetNext(m.head)
		(&m.head.ViewEntry).SetPrev(l.tail)
		l.tail = m.tail
	}
	m.head = nil
	m.tail = nil
}

