// Code generated by locking.bzl. DO NOT EDIT.

package tcp

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type forwarderRequestMutex struct {
	mu sync.Mutex
}

// Lock locks m.
// +checklocksignore
func (m *forwarderRequestMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *forwarderRequestMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *forwarderRequestMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *forwarderRequestMutex) NestedUnlock() {
	m.mu.Unlock()
}

