// Code generated by locking.bzl. DO NOT EDIT.

package tcp

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type protocolRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *protocolRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *protocolRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *protocolRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *protocolRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *protocolRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *protocolRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *protocolRWMutex) RLocker() sync.Locker {
	return (*protocolRWMutexRLocker)(m)
}

type protocolRWMutexRLocker protocolRWMutex

func (r *protocolRWMutexRLocker) Lock()   { (*protocolRWMutex)(r).RLock() }
func (r *protocolRWMutexRLocker) Unlock() { (*protocolRWMutex)(r).RUnlock() }

