// Code generated by locking.bzl. DO NOT EDIT.

package tcp

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type sndQueueMutex struct {
	mu sync.Mutex
}

// Lock locks m.
// +checklocksignore
func (m *sndQueueMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *sndQueueMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *sndQueueMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *sndQueueMutex) NestedUnlock() {
	m.mu.Unlock()
}

