// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package tcp

// segmentEntry is an entry in a segmentList.
type segmentEntry struct {
	next *segment
	prev *segment
}

// Next returns the entry that follows e in the list.
func (e *segmentEntry) Next() *segment {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *segmentEntry) Prev() *segment {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *segmentEntry) SetNext(entry *segment) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *segmentEntry) SetPrev(entry *segment) {
	e.prev = entry
}

// segmentList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for segmentList is an empty list ready to use.
type segmentList struct {
	head *segment
	tail *segment
}

// Reset resets list l to the empty state.
func (l *segmentList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *segmentList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *segmentList) Front() *segment {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *segmentList) Back() *segment {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *segmentList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *segmentList) PushFront(e *segment) {
	linker := &e.segmentEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.segmentEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *segmentList) PushBack(e *segment) {
	linker := &e.segmentEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.segmentEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// InsertAfter inserts e after b.
func (l *segmentList) InsertAfter(b, e *segment) {
	bLinker := &b.segmentEntry
	eLinker := &e.segmentEntry

	a := bLinker.Next()

	eLinker.SetNext(a)
	eLinker.SetPrev(b)
	bLinker.SetNext(e)

	if a != nil {
		(&a.segmentEntry).SetPrev(e)
	} else {
		l.tail = e
	}
}

// Remove removes e from l.
func (l *segmentList) Remove(e *segment) {
	linker := &e.segmentEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.segmentEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.segmentEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

