// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package tcp

// endpointEntry is an entry in an endpointList.
type endpointEntry struct {
	next *Endpoint
	prev *Endpoint
}

// Next returns the entry that follows e in the list.
func (e *endpointEntry) Next() *Endpoint {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *endpointEntry) Prev() *Endpoint {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *endpointEntry) SetNext(entry *Endpoint) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *endpointEntry) SetPrev(entry *Endpoint) {
	e.prev = entry
}

// endpointList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for endpointList is an empty list ready to use.
type endpointList struct {
	head *Endpoint
	tail *Endpoint
}

// Reset resets list l to the empty state.
func (l *endpointList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *endpointList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *endpointList) Front() *Endpoint {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *endpointList) Back() *Endpoint {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *endpointList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *endpointList) PushFront(e *Endpoint) {
	linker := &e.endpointEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.endpointEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *endpointList) PushBack(e *Endpoint) {
	linker := &e.endpointEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.endpointEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// Remove removes e from l.
func (l *endpointList) Remove(e *Endpoint) {
	linker := &e.endpointEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.endpointEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.endpointEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

