// Copyright 2018 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go_generics. DO NOT EDIT.

package raw

// rawPacketEntry is an entry in a rawPacketList.
type rawPacketEntry struct {
	next *rawPacket
	prev *rawPacket
}

// Next returns the entry that follows e in the list.
func (e *rawPacketEntry) Next() *rawPacket {
	return e.next
}

// Prev returns the entry that precedes e in the list.
func (e *rawPacketEntry) Prev() *rawPacket {
	return e.prev
}

// SetNext assigns 'entry' as the entry that follows e in the list.
func (e *rawPacketEntry) SetNext(entry *rawPacket) {
	e.next = entry
}

// SetPrev assigns 'entry' as the entry that precedes e in the list.
func (e *rawPacketEntry) SetPrev(entry *rawPacket) {
	e.prev = entry
}

// rawPacketList is an intrusive list. Entries can be added to or removed from the
// list in O(1) time and with no additional memory allocations.
//
// The zero value for rawPacketList is an empty list ready to use.
type rawPacketList struct {
	head *rawPacket
	tail *rawPacket
}

// Reset resets list l to the empty state.
func (l *rawPacketList) Reset() {
	l.head = nil
	l.tail = nil
}

// Empty returns true iff the list is empty.
func (l *rawPacketList) Empty() bool {
	return l.head == nil
}

// Front returns the first element of list l or nil.
func (l *rawPacketList) Front() *rawPacket {
	return l.head
}

// Back returns the last element of list l or nil.
func (l *rawPacketList) Back() *rawPacket {
	return l.tail
}

// Len returns the number of elements in the list.
//
// NOTE: This is an O(n) operation.
func (l *rawPacketList) Len() (count int) {
	for e := l.Front(); e != nil; e = e.Next() {
		count++
	}
	return count
}

// PushFront inserts the element e at the front of list l.
func (l *rawPacketList) PushFront(e *rawPacket) {
	linker := &e.rawPacketEntry
	linker.SetNext(l.head)
	linker.SetPrev(nil)
	if l.head != nil {
		(&l.head.rawPacketEntry).SetPrev(e)
	} else {
		l.tail = e
	}
	l.head = e
}

// PushBack inserts the element e at the back of list l.
func (l *rawPacketList) PushBack(e *rawPacket) {
	linker := &e.rawPacketEntry
	linker.SetNext(nil)
	linker.SetPrev(l.tail)
	if l.tail != nil {
		(&l.tail.rawPacketEntry).SetNext(e)
	} else {
		l.head = e
	}
	l.tail = e
}

// Remove removes e from l.
func (l *rawPacketList) Remove(e *rawPacket) {
	linker := &e.rawPacketEntry
	prev := linker.Prev()
	next := linker.Next()

	if prev != nil {
		(&prev.rawPacketEntry).SetNext(next)
	} else if l.head == e {
		l.head = next
	}

	if next != nil {
		(&next.rawPacketEntry).SetPrev(prev)
	} else if l.tail == e {
		l.tail = prev
	}

	linker.SetNext(nil)
	linker.SetPrev(nil)
}

