// Code generated by locking.bzl. DO NOT EDIT.

package packet

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type rcvMutex struct {
	mu sync.Mutex
}

// Lock locks m.
// +checklocksignore
func (m *rcvMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *rcvMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *rcvMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *rcvMutex) NestedUnlock() {
	m.mu.Unlock()
}

