// Code generated by locking.bzl. DO NOT EDIT.

package packet

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type endpointRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *endpointRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *endpointRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *endpointRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *endpointRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *endpointRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *endpointRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *endpointRWMutex) RLocker() sync.Locker {
	return (*endpointRWMutexRLocker)(m)
}

type endpointRWMutexRLocker endpointRWMutex

func (r *endpointRWMutexRLocker) Lock()   { (*endpointRWMutex)(r).RLock() }
func (r *endpointRWMutexRLocker) Unlock() { (*endpointRWMutex)(r).RUnlock() }

