// Code generated by locking.bzl. DO NOT EDIT.

package packet

import (
	"gvisor.dev/gvisor/pkg/sync"
)

// +checklocksignore
type packetMmapRWMutex struct {
	mu sync.RWMutex
}

// Lock locks m.
// +checklocksignore
func (m *packetMmapRWMutex) Lock() {
	m.mu.Lock()
}

// NestedLock locks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetMmapRWMutex) NestedLock() {
	m.mu.Lock()
}

// Unlock unlocks m.
// +checklocksignore
func (m *packetMmapRWMutex) Unlock() {
	m.mu.Unlock()
}

// NestedUnlock unlocks m knowing that another lock of the same type is held.
// +checklocksignore
func (m *packetMmapRWMutex) NestedUnlock() {
	m.mu.Unlock()
}

// RLock locks m for reading.
// +checklocksignore
func (m *packetMmapRWMutex) RLock() {
	m.mu.RLock()
}

// RUnlock undoes a single RLock call.
// +checklocksignore
func (m *packetMmapRWMutex) RUnlock() {
	m.mu.RUnlock()
}

// RLocker returns a Locker interface that implements Lock and Unlock by calling
// RLock and RUnlock on m.
func (m *packetMmapRWMutex) RLocker() sync.Locker {
	return (*packetMmapRWMutexRLocker)(m)
}

type packetMmapRWMutexRLocker packetMmapRWMutex

func (r *packetMmapRWMutexRLocker) Lock()   { (*packetMmapRWMutex)(r).RLock() }
func (r *packetMmapRWMutexRLocker) Unlock() { (*packetMmapRWMutex)(r).RUnlock() }

