server {
    listen 80;
    listen 443 ssl;
    server_name origin;

    ssl_certificate     /etc/nginx/tls/origin.crt;
    ssl_certificate_key /etc/nginx/tls/origin.key;

    root  /usr/share/nginx/html;
    index index.html;
}
